### PR TITLE
Add mix method and useful package.json stuff

### PR DESCRIPTION
**Pull request by ThomWright**

### CODE REVIEW

**Comment by neojski** [comment]
Thank you @ThomWright!

**Comment by ThomWright** [comment]
No worries, big fan of the library. Victor is great but it bit me in the ass when it started mutating all over the place! I'll add in some more methods as and when I need them.

**Comment by neojski** [comment]
I created this one for the same reason. Feel free to add more methods as you need them :-)

**Comment by neojski** [comment]
Now I'm thinking that maybe we should have named it [lerp](http://en.wikipedia.org/wiki/Lerp_%28computing%29).

Let's defer worrying about that until version 1.0.

**Comment by ThomWright** [comment]
We can always have both, and simply use one as an alias. This way we keep consistent with the Victor API, which is well documented and what users will expect, as well as having a more correct name.

**Pull request merged**
